# Generated by Django 5.0.1 on 2024-01-14 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinterest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
