# Generated by Django 5.0.2 on 2024-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
