# Generated by Django 5.0.1 on 2024-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_myimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
